dist: xenial 
language: python
python:
        - "3.7"

install:
        - pip install -r requirements.developer
        - pip install concurrencytest
        - pip install .

script:
        - python tests/run_tests.py
notifications:
  email:
    recipients:
      - hmetzler.bgc-jema.mpg.de
      - csierra.bgc-jema.mpg.de
      - vceball.bgc-jema.mpg.de
    on_success: change # default: change
    on_failure: always # default: always
